In [1]:
import numpy as np

##### Basic Filtering

In [2]:
ages = np.array([25, 30, 18, 44, 21, 17, 21])

adults = ages[ages >= 18]

print(adults)

[25 30 18 44 21 21]


In [3]:
adults_age = ages[(ages > 20) & (ages < 35)]

print(adults_age)

[25 30 21 21]


In [4]:
names = np.array(["Rahul" , "Alice", "Bob", "Carlice" , "Akash"])

selected_names = names[np.char.startswith(names, "A") | np.char.startswith(names, "R")]

print(selected_names)

['Rahul' 'Alice' 'Akash']


#### Basic Masking Selection

In [5]:
temp = np.array([28, 32 , 35, 30, 22])

is_hot = temp > 30

hot_temp = temp[is_hot]

print(temp)
print(is_hot)
print(hot_temp)

[28 32 35 30 22]
[False  True  True False False]
[32 35]


#### Masing for Modification

In [6]:
temp[is_hot] = 31

print(temp)

[28 31 31 30 22]


##### np.where

In [7]:

scores = np.array([68 , 81 , 78 , 90 , 55 , 78])

# If score >= 75 -> Pass , otherwise Fail

grades = np.where(scores >= 75 , "Pass" , "")

print(scores)
print(grades)

[68 81 78 90 55 78]
['' 'Pass' 'Pass' 'Pass' '' 'Pass']


#### Reshaping a 1D to 2D

In [8]:
num_1d = np.array([1, 2, 3, 4])

num_2d = num_1d.reshape(1,4)

print(num_1d)

print(num_2d)

[1 2 3 4]
[[1 2 3 4]]


##### Broandcasting a 1D Array to a 2D Array

In [9]:
sales = np.array([[10, 20], [15,25], [12, 10]])

add_value = np.array([2, 3, 1])

print(sales)

print(add_value)

[[10 20]
 [15 25]
 [12 10]]
[2 3 1]


In [10]:
bonues_col = add_value.reshape(3,1)

sales_with_bounes = sales + bonues_col

print(sales_with_bounes)

[[12 22]
 [18 28]
 [13 11]]


In [11]:
print(bonues_col)

sales_flatten = sales_with_bounes.flatten()

print(sales_flatten)

[[2]
 [3]
 [1]]
[12 22 18 28 13 11]


In [30]:
import numpy as np

arr_1d = np.array([
    [[10, 11],
     [12, 13],
     [14, 15],
     [16, 17]]
])

arr_2d = np.array([
    [10, 11],
    [12, 13],
    [14, 15],
    [16, 17]
])

resize_arr_2d = arr_2d.reshape(2, 4)
resize_arr_1d = arr_1d.reshape(2, 4)

#result = arr_1d + resize_arr_2d

print(f"arr_2d = {resize_arr_2d} \n\n")
print(f"arr_2d = {resize_arr_1d} \n\n")

result = resize_arr_1d + resize_arr_2d

resize_result = result.reshape(4,2)

print(result)
print(resize_result)

arr_2d = [[10 11 12 13]
 [14 15 16 17]] 


arr_2d = [[10 11 12 13]
 [14 15 16 17]] 


[[20 22 24 26]
 [28 30 32 34]]
[[20 22]
 [24 26]
 [28 30]
 [32 34]]
