In [1]:
import numpy as np

##### Basic Filtering

In [ ]:
ages = np.array([25, 30, 18, 44, 21, 17, 21])

adults = ages[ages >= 18]

print(adults)

[25 30 18 44 21 21]


In [4]:
adults_age = ages[(ages > 20) & (ages < 35)]

print(adults_age)

[25 30 21 21]


In [5]:
names = np.array(["Rahul" , "Alice", "Bob", "Carlice" , "Akash"])

selected_names = names[np.char.startswith(names, "A") | np.char.startswith(names, "R")]

print(selected_names)

['Rahul' 'Alice' 'Akash']


#### Basic Masking Selection

In [6]:
temp = np.array([28, 32 , 35, 30, 22])

is_hot = temp > 30

hot_temp = temp[is_hot]

print(temp)
print(is_hot)
print(hot_temp)

[28 32 35 30 22]
[False  True  True False False]
[32 35]


#### Masing for Modification

In [10]:
temp[is_hot] = 31

print(temp)

[28 31 31 30 22]


##### np.where

In [14]:
scores = np.where([68 , 81 , 78 , 90 , 55 , 78])

# if score >= 75 -> pass otherwise fail

grades = np.where(scores >= 75 , "pass" , "Fail")

print(scores)

print(grades)

TypeError: '>=' not supported between instances of 'tuple' and 'int'