In [1]:
import math

In [2]:
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'cbrt', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'exp2', 'expm1', 'fabs', 'factorial', 'floor', 'fma', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'sumprod', 'tan', 'tanh', 'tau', 'trunc', 'ulp']


In [3]:
print("Hello World!")

Hello World!


## This is Markdown Lang.

### This is

In [4]:
import numpy as np

**1. Mathematical Operation**

In [5]:
a = np.array([
    [10, 20 ,30],
    [40, 50 ,60],
    [70, 80, 90]
])

b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Array A:")
print(a)

print("Array B:")
print(b)

print("Addition : ")
print(a + b)

print("Subtraction : ")
print(a - b)

print("Multiplication : ")
print(a * b)

print("Division : ")
print(a / b)

Array A:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Array B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Addition : 
[[11 22 33]
 [44 55 66]
 [77 88 99]]
Subtraction : 
[[ 9 18 27]
 [36 45 54]
 [63 72 81]]
Multiplication : 
[[ 10  40  90]
 [160 250 360]
 [490 640 810]]
Division : 
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]


In [6]:
print("Square Root, Expontial and Logarithmic Functions")

arr = np.array([1, 2, 3 ,4 ,5])

print("Square Root : ")
print(np.sqrt(arr))

print("Expontial : ")
print(np.exp(arr))

print("Natural Logarithmic : ")
print(np.log(arr))

print("Base 10 Logarithmic : ")
print(np.log10(arr))



Square Root, Expontial and Logarithmic Functions
Square Root : 
[1.         1.41421356 1.73205081 2.         2.23606798]
Expontial : 
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Natural Logarithmic : 
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
Base 10 Logarithmic : 
[0.         0.30103    0.47712125 0.60205999 0.69897   ]


**3. Trigonometric Operations**

In [7]:
print("Trigonometric Operations")

angle = np.array([0, 30, 45, 60, 90])

radiaus = np.deg2rad(angle)

print(np.sin(radiaus))
print(np.cos(radiaus))
print(np.tan(radiaus))

Trigonometric Operations
[0.         0.5        0.70710678 0.8660254  1.        ]
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


**4. Normalize an Array**

In [8]:
data = np.array([10, 20 ,30 ,40 ,50])

std =np.std(data)
mean = np.mean(data)

normalize = (data-mean) / std

print(data)

print(mean)

print(std)

print(normalize)

[10 20 30 40 50]
30.0
14.142135623730951
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


**2. Combining and Splitting Arrays**

In [9]:
print("Horizontal and Vertical Concatination")

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1)
print(arr2)

horizontal = np.hstack((arr1, arr2))

vertical = np.vstack((arr1, arr2))

print(horizontal)
print(vertical)


Horizontal and Vertical Concatination
[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


***# vstack, hstack and Split vsplit and hsplit***

In [10]:
print("Stack and Split Arrays")

arr1 = np.array([
    [1, 2 , 3],
    [4, 5, 6],
    [7, 8, 9]
])

arr2 = np.array([
    [7, 8, 9, 10, 11, 12],
    [13, 14, 15, 16, 17, 18]
])

print(arr1)
print(arr2)

#v_stack = np.vstack((arr1 , arr2))

#h_stack = np.hstack((arr1 , arr2))

#print(v_stack)

#print(h_stack)

v_split = np.vsplit(arr1 , 3)

#h_split = np.hsplit(arr2 , 2)

print(v_split)

#print(h_split)



Stack and Split Arrays
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


**# Flattern and Reshape 3D Array**

In [11]:
print("Flattern and Reshape 3D Array")

arr_3d = np.array([
    [[1, 2] , [3, 4]],
    [[5, 6] , [7, 8]]
])

print(arr_3d)

print(arr_3d.shape)

flat_arr = arr_3d.flatten()

print(arr_3d)

print(flat_arr)

reshape = arr_3d.reshape(arr_3d.shape)

print(reshape)

Flattern and Reshape 3D Array
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6 7 8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
